### PR TITLE
Fix Auto Layout Intercepter on Xcode 10

### PR DESCRIPTION
**Pull request by danl3v**
This PR fixes an issue with autolayout failure interceptions on Xcode 10.

### CODE REVIEW

**Comment by oliverhu** [comment]
I'd prefer just go ahead with only _latest & best_ Xcode 10 (Remove the PreXcode10 support), if a user is still with Xcode 9.x, they can piggyback on an older version.

@plivesey ^ if you have objection.

**Comment by danl3v** [comment]
Apologies for the many builds. Haven't used travis before :(

**Comment by danl3v** [comment]
I'll look into it. Maybe the sims need to be booted?

**Comment by oliverhu** [comment]
It seems the CI build failed again, could you take a look? @danl3v

**Comment by oliverhu** [comment]
We don't have control to reboot Travis's simulators, however I think Travis would clean up a box before kicking off a new task tho.

**Comment by oliverhu** [comment]
Not 100% sure, maybe we're not supposed to launch 3 simulators at the same time with Travis. We can try 2 simulators and see if it passes...

**Comment by danl3v** [comment]
@oliverhu made some headway. Looks like the iPhone SE is the magic travis ci sim. Gonna do some more testing and clean up my commits

**Comment by danl3v** [comment]
@oliverhu looks like trying to set iOS 11 as a destination is causing some issues. I can experiment more if you would like or also downgrade from 10.1 to 10.

**Comment by oliverhu** [comment]
LGTM.

**Pull request merged**
